#!/usr/bin/env bash

# Set berry decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       12
berryc top_gap            24
##berryc edge_gap           70 5 10 10

# Set berry decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   000000
berryc inner_unfocus_color 565679
berryc text_focus_color    D3D7CF
berryc text_unfocus_color  eeeeee

# Other berry options
berryc smart_place  "true"
berryc draw_text    "true"
berryc edge_lock    "true"
berryc decorate_new "true"
berryc set_font     "Roboto Condensed,Roboto Condensed Medium"
berryc manage       Dialog|Toolbar|Menu|Splash|Utility

# auto start keybindings and background
/usr/bin/sxhkd -c /home/srsantos/.config/berry/sxhkdrc &
/home/srsantos/.config/feh/fehbg_berry &

# auto start programs and set wallpaper
/usr/bin/compton --config /home/srsantos/.config/picom_compton/picom.conf &>/dev/null &
/usr/bin/xcalib -d :0 /home/srsantos/.color/icc/Monitor_5-24-2012_1.icc
/usr/local/bin/touchpad_toggle.sh &
/usr/bin/unclutter --timeout 10 --jitter 50 --exclude-root --ignore-scrolling --fork
/usr/bin/dunst -config /home/srsantos/.config/dunst/dunstrc &
/usr/bin/opensc-notify &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# auto start screensaver and locker
/usr/bin/xset s 590 10
/usr/bin/xset dpms 0 0 605
/usr/bin/xss-lock -n /usr/local/bin/dim-screen_xss-lock.sh -l -- /usr/local/bin/xsecurelock_optimized.sh &
